services:
  keycloak:
    build: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KC_HOSTNAME: "localhost"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    command:
      - start-dev --import-realm