services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - ./.config/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_PROXY: passthrough
      KC_HTTP_RELATIVE_PATH: /auth
      HTTP_ADDRESS_FORWARDING: 'true'
    volumes:
      - ./.config/hotel-app-realm.json:/opt/keycloak/data/import/hotel-app-realm.json:ro
    command:
      - start-dev --import-realm
    restart: unless-stopped

  frontend:
    build: ./frontend-app
    restart: unless-stopped

  backend:
    build: ./backend-app
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: unless-stopped